# config.yaml

directories:
    content: "content"
    template: "templates"
    script: "scripts"
    style: "styles"
    media: "media"
    output: "docs"

default_template: "base.html"

baseURL: "https://example.com"
languageCode: "en-us"

title: "My Website"
description: "This is my website"
author: "Your Name"
keywords: "website, blog, portfolio"
copyright: "© Your Name"

menu:
    - name: "Your Name"
      url: "/"
    - name: "Projects"
      url: "/projects"
    - name: "About"
      url: "/about.html"
    - name: "Contact"
      url: "/contact.html"

social:
    twitter: "username"
    github: "username"
    linkedin: "username"
    email: "username@example.com"
