name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install staticgen tool
      run: pip install git+https://github.com/leabstrait/static-gen  # Adjust this command based on your project setup

    - name: Set up docs directory
      run: |
        mkdir -p docs
        find docs/ ! -name 'CNAME' -type f -exec rm -f {} + # Delete all contents of the docs directory except CNAME
      if: success()

    - name: Run generate.py
      run: staticgen gen

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto-generated: Build and deploy to docs directory"
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
      if: success()

    - name: Push changes to GitHub
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: success()
